### ISSUE TITLE
New RuntimeError of ss_vae_M2.py with -cuda option

### ISSUE THREAD

**Issue by jinserk** [uber/pyro#750]
Hello. With the latest pytorch update (`0.4.0a0+bf60329`) and pyro (`53bf515`), I've got a new error as:
```
$ python ss_vae_M2.py -cuda
THCudaCheck FAIL file=/home/jbaik/setup/pytorch/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu line=410 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "ss_vae_M2.py", line 450, in <module>
    run_inference_ss_vae(args)
  File "ss_vae_M2.py", line 357, in run_inference_ss_vae
    run_inference_for_epoch(data_loaders, losses, periodic_interval_batches)
  File "ss_vae_M2.py", line 254, in run_inference_for_epoch
    new_loss = losses[loss_id].step(xs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 146, in loss_and_grads
    for weight, model_trace, guide_trace, log_r in self._get_traces(model, guide, *args, **kwargs):
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/infer/trace_elbo.py", line 87, in _get_traces
    guide_trace = poutine.trace(guide).get_trace(*args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/poutine/trace_poutine.py", line 250, in get_trace
    self(*args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/poutine/trace_poutine.py", line 238, in __call__
    ret = super(TracePoutine, self).__call__(*args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/poutine/poutine.py", line 147, in __call__
    return self.fn(*args, **kwargs)
  File "ss_vae_M2.py", line 154, in guide
    pyro.sample("z", dist.normal, mu, sigma, extra_event_dims=1)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/__init__.py", line 87, in sample
    apply_stack(msg)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/util.py", line 243, in apply_stack
    default_process_message(msg)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/util.py", line 53, in default_process_message
    val = fn(*args, **kwargs)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/distributions/random_primitive.py", line 46, in sample
    return self.dist_class(*args, **kwargs).sample(sample_shape)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pyro_ppl-0.1.2-py3.6.egg/pyro/distributions/torch_wrapper.py", line 39, in sample
    return self.torch_dist.rsample(sample_shape)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torch/distributions/normal.py", line 59, in rsample
    return self.loc + eps * self.scale
RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/jbaik/setup/pytorch/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:410
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [43,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [21,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [36,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [52,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [56,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [7,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(sum
, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [11,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [59,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [14,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [8,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(sum
, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [23,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
/home/jbaik/setup/pytorch/pytorch/aten/src/THC/THCTensorRandom.cuh:193: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [25,0,0], thread: [0,0,0] Assertion `THCNumerics<AccT>::gt(su
m, accZero)` failed.
```

**Comment by eb8680** [comment]
Hi, I suspect this issue has the same underlying cause as the one in [this Pyro forum thread](https://forum.pyro.ai/t/ss-vae-unsupervised-loss-problems/103).  There was a recent change (#695 ) that added drawing a single sample internally before enumerating to infer the correct shape of the enumerated values, and this error seems to be caused by invalid weights in that sampling step.

**Comment by fritzo** [comment]
Sounds like we should instead call `site["fn"].shape()` and and deprecate `RandomizedPrimitive`.

**Comment by eb8680** [comment]
> Sounds like we should instead call site["fn"].shape() and and deprecate RandomizedPrimitive

Agreed, but that doesn't address the underlying cause of this issue and the one on the forum, which is the imbalanced categorical weights.  We should figure out how to make this example more stable.

**Comment by jinserk** [comment]
Could you let me know if there is any workaround? I have also zero loss for unsupervised samples as described in [Pyro forum thread](https://forum.pyro.ai/t/ss-vae-unsupervised-loss-problems/103)

**Comment by fritzo** [comment]
Sorry @jinserk I haven't had time to diagnose the underlying cause. I think your best options are to either use Pyro 0.1.2 release or wait a few weeks until Pyro dev branch stabilizes. We're currently in the middle of a big refactoring to support PyTorch distributions, distribution broadcasting, multiple batch dimensions, nested `iarange`s, and parallel `enum_discrete`.

If you have time to help us diagnose this, it would be really helpful to grab the `logits` or `probs` arg to the `Multinomial` or `Categorical` sampler that is causing the cuda failure. If we can narrow this down to a reproducible test case, I could submit numerical stability fixes upstream to PyTorch.

**Comment by fehiepsi** [comment]
@jinserk How is it going? I use pytorch with commit `ca5071d07` as suggested at https://github.com/uber/pyro/blob/dev/README.md and the current dev branch. The `-cuda` option works for me and I did not see the zero loss issue for unsupervised examples.

**Comment by jinserk** [comment]
Thanks @fehiepsi ! I figured out the latest update of pyro changed the example ss_vae code, but I have a running training so couldn't update it. Will check it soon!

**Comment by jinserk** [comment]
I've update pytorch and pyro and tested `ss_vae_M2.py` with `-cuda` option. It seems works! Thanks for the great job!
